// <auto-generated />
namespace Northwind.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Northwindv10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Northwindv10));
        
        string IMigrationMetadata.Id
        {
            get { return "202003281930425_Northwind-v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
